### PR TITLE
feat: add icons from dropdown

### LINKED ISSUE #8: [Feat]: get icons from dropdown
### Feature request

Get icons from dropdown

### PR DESCRIPTION
**Pull request by darkterminal**
Add icons selection from dropdown resolve #8

## Screenshot
image

### CODE REVIEW

**Review by emmalearnscode — COMMENTED** [review]
This is an interesting idea but I wonder how we will make sure that Tom's site and Linkfree are kept in sync with each other in case new icons are added 🤔 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by darkterminal** [comment]
I think from now we can keep this changed, coz from LinkFree Repository just have markdown instead of `json` [icon.md](https://github.com/EddieHubCommunity/LinkFree/blob/main/icons.md?plain=1)

**Comment by schmelto** [comment]
> This is an interesting idea but I wonder how we will make sure that Tom's site and Linkfree are kept in sync with each other in case new icons are added 🤔
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  ❓ I have a question

I think this is something we can tackle in another issue. :) but great thoughts!

**Comment by darkterminal** [comment]
@schmelto Need Pull Request to LinkFree Repository about icon.json?

**Pull request merged**
